language: php
php:
  - '5.6'
  - '7.0'
  - 'nightly'
  - 'hhvm'
env:
  matrix:
    - COMPOSER_ARGS="update --prefer-lowest"
    - COMPOSER_ARGS="update"
install:
  - 'composer $COMPOSER_ARGS'
script:
  - 'vendor/bin/phpunit tests'